running but with bugs

diff --git a/suriGUI b/suriGUI
--- a/suriGUI
+++ b/suriGUI
@@ -11,52 +11,107 @@ set -o pipefail     # Pipe return exit status
 trap 'echo "$BASH_COMMAND" failed with error code $?' ERR
 
 
+if [ "$EUID" -ne 0 ]
+  then echo "Please run as root"
+  exit 1
+fi
+
+
+function d3bug() {
+  case "${1:-*}" in
+    "info" )    echo "$(date +"%H:%M:%S") |   |__ $2" ;;
+    "error" )   echo -e "$(date +"%H:%M:%S") |__ \e[41;30m$2\e[0m" ;;
+    *)          echo "$(date +"%H:%M:%S") |__ ${FUNCNAME[1]}" ;;
+  esac
+}
+export -f d3bug
+
+
 function createDir() {
-  [[ ! -d "$1" ]] && mkdir -p "$1" || return 0
+  if [[ ! -d "$1" ]]; then
+    mkdir -p "$1"
+    d3bug info "Directory created: $1"
+  else
+    d3bug info "Directory found: $1"
+  fi
 }
 export -f createDir
+
 
 export dateShort=$(date +"%H:%M:%S")
 export dateLong=$(date +"%Y-%m-%d-%H-%M-%S")
 
+export _PROJECT_NAME="suriGUI" && echo -e "$dateShort \e[42;30m  $_PROJECT_NAME  \e[0m"
 
-export _PROJECT_NAME="suriGUI" && echo -e "$dateShort \e[42;30m$_PROJECT_NAME\e[0m"
-
-export _PROJECT_VER="0.4"
-export _PROJECT_BUILD="2021-11-30"
+export _PROJECT_VER="0.5"
+export _PROJECT_BUILD="2021-12-04"
 export _PROJECT_DIR="/usr/share/suriGUI"        && createDir "${_##*=}"
 export _PROJECT_DIR_RES="$_PROJECT_DIR/res"     && createDir "${_##*=}"
 export _PROJECT_DIR_TMP="$_PROJECT_DIR/tmp"     && createDir "${_##*=}"
 export _PROJECT_DIR_CONF="$_PROJECT_DIR/conf"   && createDir "${_##*=}"
 export _PROJECT_DIR_LOG="$_PROJECT_DIR/log"     && createDir "${_##*=}"
 
-export _PROJECT_CONFIG="$_PROJECT_DIR_CONF/suri.conf"
-
+export _PROJECT_CONFIG_FILE="$_PROJECT_DIR_CONF/suriGUI.conf"
+export _PROJECT_PIPE="$_PROJECT_DIR_TMP/suri.pipe"
 
 export _PROJECT_ICON_INACTIVE="$_PROJECT_DIR_RES/inactive-icon.png"
 export _PROJECT_ICON_ACTIVE="$_PROJECT_DIR_RES/active-icon.png"
-export _PROJECT_PIPE="$_PROJECT_DIR_TMP/suri.pipe"
 
-export _SURICATA_CONFIG="$_PROJECT_DIR_CONF/suricata.yaml"
-export _SURICATA_CONFIG_IPS="$_PROJECT_DIR_CONF/ips.yaml"
+export _SURICATA_CONFIG_IDS="$_PROJECT_DIR_CONF/suricataIDS.yaml"
+export _SURICATA_CONFIG_IPS="$_PROJECT_DIR_CONF/suricataIPS.yaml"
 export _SURICATA_RULES="$_PROJECT_DIR_CONF/suricata.rules"
-export _SURICATA_LOG="$_PROJECT_DIR_LOG/$_PROJECT_NAME-$dateLong.log"
 export _SURICATA_UPDATE_TIMESTAMP="$_SURICATA_RULES.timestamp"
+export _SURICATA_LOG="$_PROJECT_DIR_LOG/$_PROJECT_NAME-$dateLong.log"
 export _SURICATA_OUTDATE="14"
-
+export _SURICATA_PID="$_PROJECT_DIR_TMP/suricata.pid"
 
 
 function exitSuriGUI() {
-  [[ -e $_PROJECT_PIPE ]] && rm "$_PROJECT_PIPE"
+  echo -e "$dateShort \e[41;30m  EXITING  \e[0m"
 
-  echo -e "$dateShort \e[41;30mEXIT\e[0m"
-  #
-  #better exit. kill parent and all children :D
-  #
-  pkill -f "$_PROJECT_NAME-$_PROJECT_VER"
+  [[ -p $_PROJECT_PIPE ]] && exec 3<>$_PROJECT_PIPE echo "quit" >&3 &
+  exec 3<&-
+  rm $_PROJECT_PIPE 1>&- 2>&-
+
+  for f in $(ls -1 $_PROJECT_DIR_TMP/*.pid) ; do
+    d3bug info "Closing $f with PID $(cat $f)"
+    kill -9 $(cat $f) 1>&- 2>&-
+    rm $f
+  done
+  stopSuricataService exit
+
+  #[[ -d $_PROJECT_DIR_TMP ]] && rm "$_PROJECT_DIR_TMP" -R
+
 }
 export -f exitSuriGUI
-trap exitSuriGUI SIGINT SIGTERM EXIT
+trap exitSuriGUI SIGINT SIGHUP SIGTERM SIGUSR1 SIGUSR2
+trap "rm $_PROJECT_DIR_TMP -R" EXIT
+
+function checkRequirements () {
+  d3bug
+
+  apps=( libnetfilter-queue-dev suricata jq libnotify-bin )
+
+  for i in "${apps[@]}" ; do
+    if dpkg -s $i &>/dev/null; then
+      d3bug info "$i installed"
+    else
+      d3bug error "$i not found"
+
+      yad --title="$_PROJECT_NAME" --text="$i is not installed.\nDo you want to install it now?" --button="Yes" --button="No"
+      ret=$?
+      if [ $ret = 0 ] ; then
+       apt-get install $i -y
+      else
+       exit 1
+      fi
+    fi
+  done
+
+  if systemctl is-active --quiet suricata; then systemctl disable suricata && systemctl stop suricata ; fi
+
+}
+export -f checkRequirements
 
 
 function createProjectPipe() {
@@ -76,66 +131,90 @@ function createProjectPipe() {
 export -f createProjectPipe
 
 
-function d3bug() {
-  d=$(date +"%H:%M:%S")
-
-  case "${3:-*}" in
-    "next" )    level="|    |__" ;;
-    *)          level="|__" ;;
-  esac
-
-  case "${1:-*}" in
-    "info" )    echo "$dateShort |   $level $2" ;;
-    "error" )   echo -e "$dateShort $level \e[41;30m$2\e[0m" ;;
-    *)          echo "$dateShort $level ${FUNCNAME[1]}" ;;
-  esac
-}
-export -f d3bug
-
-
-function updateSuriGUISettings(){
+function createProjectPipe() {
   d3bug
-  sed -i "s/^\($1\s*=\s*\).*\$/\1$2/" "$_PROJECT_CONFIG"
+
+  [[ -e $_PROJECT_PIPE ]] && rm "$_PROJECT_PIPE"
+
+  if mkfifo "$_PROJECT_PIPE" ; then
+    d3bug info "Pipe created"
+  else
+    d3bug error "Can't create pipe"
+    exit 1
+  fi
+
+  exec 3<> "$_PROJECT_PIPE" && d3bug info "Pipe started"
 }
-export -f updateSuriGUISettings
+export -f createProjectPipe
 
 
 
-function loadSuriGUIConfig() {
-  source $_PROJECT_CONFIG
 
-  case $1 in
-    action )
+
+
+function readConfigFile() {
+  source "$_PROJECT_CONFIG_FILE"
+
+  case "$1" in
+    "action" )
       defaultActions="alert\!pass\!drop\!reject\!rejectsrc\!rejectdst\!rejectboth"
       makeDefault="^"
       export newMenu=$(echo "$defaultActions" | sed "s/$action/$makeDefault$action/g")
     ;;
+    "mode" )
+      defaultMode="IDS\!IPS"
+      makeDefault="^"
+      export newMode=$(echo "$defaultMode" | sed "s/$mode/$makeDefault$mode/g")
+    ;;
   esac
-}
-export -f loadSuriGUIConfig
 
+
+}
+export -f readConfigFile
 
 
 function updateSuricataAction() {
   d3bug
 # call old action
-  loadSuriGUIConfig action
+  readConfigFile action
 
   echo "old action: $action"
   echo "new action: $1"
   sed -i "s/$action/$1/" "$_SURICATA_RULES"
-  updateSuriGUISettings "action" $1
+  updateConfigFile "action" $1
 }
 export -f updateSuricataAction
 
 
 
+function updateSuricataMode() {
+  d3bug
+
+  d3bug info "Stopping Suricata service"
+
+  stopSuricataService
+
+  readConfigFile action
+  d3bug info "Suricata old mode: $mode"
+  d3bug info "Suricata new mode: $1"
+
+  updateConfigFile "mode" $1
+  startSuricataService
 
 
 
 
+}
+export -f updateSuricataMode
 
 
+
+function updateConfigFile() {
+  d3bug
+  sed -i "s/^\($1\s*=\s*\).*\$/\1$2/" "$_PROJECT_CONFIG_FILE"
+  d3bug info "Config updated $1 = $2"
+}
+export -f updateConfigFile
 
 
 
@@ -144,19 +223,21 @@ function suriGUISettings() {
   d3bug
 
   KEY=$RANDOM
-loadSuriGUIConfig action
+
   yad --plug=$KEY --tabnum=1 --form \
-      --field=$"Title:" "${title:-Terminal}" &
+      --field="<b>In developement</b>":LBL "" \ &
+  #echo $! > "$_PROJECT_DIR_TMP/tab1.pid"
 
+  readConfigFile mode
 
-  yad --plug=$KEY --tabnum=2 --form  \
-      --field="":LBL "" \
+  yad --plug=$KEY --tabnum=2 --form \
       --field="<b>Mode</b>":LBL "" \
-      --field="Suricata mode":CB "IDS\!^IPS" \
+      --field="Suricata mode":CB "$newMode" \
+      --field="Apply":fbtn 'bash -c "updateSuricataMode %2"' \
       \
       --field="":LBL "" \
       --field="<b>Files</b>":LBL "" \
-      --field="Suricata config file:":FL "$_SURICATA_CONFIG" \
+      --field="IDS config file:":FL "$_SURICATA_CONFIG_IDS" \
       --field="IPS config file:":FL "$_SURICATA_CONFIG_IPS" \
       --field="Suricata rules:":FL "$_SURICATA_RULES" \
       \
@@ -167,7 +248,9 @@ loadSuriGUIConfig action
       \
       --file-filter="Yaml files (*.yaml)| *.yaml" --file-filter="Config Files (*.cfg *.conf)| *.cfg *.conf" \
       --file-filter="All Files | *.*" &
+  #echo $! > "$_PROJECT_DIR_TMP/tab2.pid"
 
+  readConfigFile action
 
   yad --plug=$KEY --tabnum=3 --form \
       --field="Default rule action":CB "$newMenu" \
@@ -178,7 +261,12 @@ loadSuriGUIConfig action
       --field="<b>rejectsrc</b> - same as just reject":LBL "" \
       --field="<b>rejectdst</b> - send RST/ICMP error packet to receiver of the matching packet.":LBL "" \
       --field="<b>rejectboth</b> - send RST/ICMP error packets to both sides of the conversation.":LBL "" \
-      --field="Apply":fbtn 'bash -c "updateSuricataAction %1"' &
+      --field="Apply":fbtn 'bash -c "updateSuricataAction %1"' \
+      --field="":LBL "" \
+      --field="<b>Update</b>":LBL "" \
+      --field="Number:NUM" "0\!10..60\!1\!1" \
+      --field="Apply":fbtn 'bash -c "updateSuricataAction %12"' &
+  #echo $! > "$_PROJECT_DIR_TMP/tab3.pid"
 
 
   TXT=$"  <b>$_PROJECT_NAME</b>   Version: <b>$_PROJECT_VER</b>    Build: <b>$_PROJECT_BUILD</b>\\n\\n"
@@ -186,11 +274,12 @@ loadSuriGUIConfig action
   TXT+=$"  Kernel: $(uname -sr)\\n\\n"
   TXT+="  <i>$(uptime)</i>"
 
-  yad --notebook --width=600 --height=450 --center  \
+  yad --notebook --width=600 --height=350 --center --auto-kill \
       --title=$"suriGUI Settings" --text="$TXT" \
       --window-icon="utilities-terminal" --image="utilities-terminal" --image-on-top \
-      --button="Cancel" --button="Save":"bash -c suricataSaveSettings" \
-      --key=$KEY --tab=$"suriGUI" --tab=$"Suricata" --tab=$"Rules"
+      --no-buttons --auto-kill \
+      --key=$KEY --tab=$"suriGUI" --tab=$"Suricata" --tab=$"Rules" &
+  #echo $! > "$_PROJECT_DIR_TMP/notebook.pid"
 
 }
 export -f suriGUISettings
@@ -211,14 +300,19 @@ export -f suriOnClick
 function stopSuricataService() {
   d3bug
 
-  if systemctl stop suricata ; then
-    d3bug info "Suricata service stopped"
-  else
-    d3bug error "Can't stop Suricata service"
-    exit 1
-  fi
+  suricatasc -c shutdown 1>&- 2>&-
 
-  updateTrayMenu inactive
+  # case $1 in
+  #   exit ) : ;;
+  #   *)
+  #     sleep 5
+  #     d3bug info "Suricata stopped"
+  #     updateTrayMenu inactive
+      # [[ -f $_SURICATA_PID ]] && rm $_SURICATA_PID
+  #   ;;
+  # esac
+
+
 
 }
 export -f stopSuricataService
@@ -226,41 +320,21 @@ export -f stopSuricataService
 
 function startSuricataService() {
   d3bug
-#
-#
-#
-#
-#
-#
-#
-#
-  #start suricata service based on my Settings
-  #
-  #
-  #
-  #
-  #
-  #
-  #
 
+  source "$_PROJECT_CONFIG_FILE"
 
-  case $(systemctl is-active suricata) in
-    active )
-      d3bug info "Suricata service already running"
-      updateTrayMenu active
+  case "$mode" in
+    "IDS" ) config="-c $_SURICATA_CONFIG_IDS -i eth0"
       ;;
-    *)
-
-      if systemctl start suricata ; then
-        d3bug info "Suricata service started"
-        updateTrayMenu active
-      else
-        d3bug error "Error starting Suricata service"
-        updateTrayMenu inactive
-      fi
-    ;;
+    "IPS" ) config="-c $_SURICATA_CONFIG_IPS -q 0"
+      ;;
+    * ) d3bug error "Suricata mode unknown."
+        exit 1
+      ;;
   esac
+  d3bug info "Starting Suricata in $mode mode"
 
+  /usr/bin/suricata $config --pidfile $_SURICATA_PID -S $_SURICATA_RULES  -l $_PROJECT_DIR_LOG  1>&- 2>&- &
 }
 export -f startSuricataService
 
@@ -268,9 +342,9 @@ export -f startSuricataService
 function updateTrayIcon() {
   d3bug
 
-  exec 3<>$_PROJECT_PIPE echo "icon:$_PROJECT_NAME-$1" >&3 &
+  [[ -p $_PROJECT_PIPE ]] && exec 3<>$_PROJECT_PIPE echo "icon:$_PROJECT_NAME-$1" >&3 &
 
-  d3bug info "Tray icon updated"
+  d3bug info "Tray icon updated: $1"
 
 }
 export -f updateTrayIcon
@@ -279,43 +353,47 @@ export -f updateTrayIcon
 function updateTrayMenu() {
   d3bug
 
-  case "$*" in
+  case "$1" in
     "active") menu="Stop!bash -c stopSuricataService" ;;
     "inactive") menu="Start!bash -c startSuricataService" ;;
     *)    exit 1          ;;
   esac
 
 
-  menu+="|Status!bash -c checkSuricataService||Settings!bash -c suriGUISettings"
+  menu+="|Status!bash -c checkSuricataStatus||Settings!bash -c suriGUISettings"
   menu+="||Exit!bash -c exitSuriGUI"
 
-  exec 3<>$_PROJECT_PIPE echo "menu:$menu" >&3 &
+  [[ -p $_PROJECT_PIPE ]] && exec 3<>$_PROJECT_PIPE echo "menu:$menu" >&3 &
 
-  d3bug info "Menu updated"
+  d3bug info "Menu updated: $1"
 
   updateTrayIcon $1
 }
 export -f updateTrayMenu
 
 
-function checkSuricataService() {
+function checkSuricataStatus() {
   d3bug
 
-  case $(systemctl is-active suricata) in
-    active )
-      d3bug info "Suricata service is active"
-      updateTrayMenu active
-      export suricataServiceStatus=active
-    ;;
-    * )
-      d3bug info "Suricata service: inactive"
+  # if [[ -f $_SURICATA_PID ]] ; then
+    if ps -p $(cat $_SURICATA_PID 2>/dev/null) &>/dev/null; then
+        d3bug info "Suricata is active"
+        updateTrayMenu active
+        export suricataStatus=active
+    else
+      #rm $_SURICATA_PID
+      d3bug info "Suricata is inactive"
       updateTrayMenu inactive
-      export suricataServiceStatus=inactive
-    ;;
-  esac
-
+      export suricataStatus=inactive
+    fi
+  # else
+  #   #rm $_SURICATA_PID
+  #   d3bug info "Suricata is inactive"
+  #   updateTrayMenu inactive
+  #   export suricataStatus=inactive
+  # fi
 }
-export -f checkSuricataService
+export -f checkSuricataStatus
 
 
 function updateSuricataRules() {
@@ -337,24 +415,32 @@ function updateSuricataRules() {
     fi
   fi
 
-  d3bug info "Updating..."
+#check for mode
 
-  if suricata-update --output "$_PROJECT_DIR_CONF" \
-                     --config "$_SURICATA_CONFIG" \
-                     --data-dir "$_PROJECT_DIR_CONF" \
-                     --no-test >/dev/null ; then
-    if suricatasc -c ruleset-reload-nonblocking ; then
-      d3bug info "Rules reloaded"
+
+
+  if command -v suricata-update ; then
+    if suricata-update --output "$_PROJECT_DIR_CONF" \
+                       --data-dir "$_PROJECT_DIR_CONF" \
+                       --no-test >/dev/null ; then
+      if suricatasc -c ruleset-reload-nonblocking ; then
+        d3bug info "Rules reloaded"
+      else
+        d3bug error "New rules can not be applied. Exiting..."
+        exit 1
+      fi
+
+      echo "$dateShort" > "$_SURICATA_UPDATE_TIMESTAMP"
+      d3bug info "Update finished."
+      updateConfigFile action alert
     else
-      d3bug error "New rules can not be applied. Exiting..."
+      d3bug error "Error updating Suricata rules. Exiting..."
       exit 1
     fi
-
-    echo "$(date +"%Y-%m-%d")" > "$_SURICATA_UPDATE_TIMESTAMP"
-    d3bug info "Update finished."
   else
-    d3bug error "Error updating Suricata rules. Exiting..."
+    d3bug error "suricata-update not installed. Aborting"
     exit 1
+
   fi
 
 }
@@ -364,7 +450,7 @@ export -f updateSuricataRules
 function checkSuricataRules() {
   d3bug
 
-  if [[ -f $_SURICATA_UPDATE_TIMESTAMP ]]; then
+  if [[ -f "$_SURICATA_UPDATE_TIMESTAMP" ]]; then
     if [[ $(cat $_SURICATA_UPDATE_TIMESTAMP) =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
       export lastUpdate="$((($(date +%s)-$(date +%s --date $(cat $_SURICATA_UPDATE_TIMESTAMP)))/(3600*24)))"
       #d3bug info "Rules old $lastUpdate days"
@@ -387,7 +473,7 @@ function checkSuricataRules() {
 export -f checkSuricataRules
 
 
-function startSuriDaemon() {
+function startSuriGUIDaemon() {
   d3bug
 
   d3bug info "Starting $_PROJECT_NAME $_PROJECT_VER"
@@ -405,31 +491,37 @@ function startSuriDaemon() {
 
   d3bug info "Icons created"
 
-  exec -a "$_PROJECT_NAME-$_PROJECT_VER" \
-    yad --notification --no-middle --listen \
-      --text="$_PROJECT_NAME v$_PROJECT_VER" \
-      --image="$_PROJECT_NAME-inactive" \
-      --separator="|" \
-      --menu="${suriTrayMenuList:-Exit!bash -c exitSuriGUI}" \
-      --command="bash -c suriOnClick" <&3 &
+  yad --notification --no-middle --listen \
+    --text="$_PROJECT_NAME v$_PROJECT_VER" \
+    --image="$_PROJECT_NAME-inactive" \
+    --separator="|" \
+    --menu="${suriTrayMenuList:-Exit!bash -c exitSuriGUI}" \
+    --command="bash -c suriOnClick" <&3 &
+  echo $! > "$_PROJECT_DIR_TMP/suriGUIDaemon.pid"
 
   d3bug info "Daemon started"
 }
-export -f startSuriDaemon
+export -f startSuriGUIDaemon
 
-
+checkRequirements
 createProjectPipe
-
 checkSuricataRules
-checkSuricataService
-[[ $suricataServiceStatus != "active" ]] && startSuricataService
-startSuriDaemon
+checkSuricataStatus
+#[[ $suricataStatus != "active" ]] && startSuricataService
+startSuriGUIDaemon
 
 
-while [[ -e $_PROJECT_PIPE ]]; do
-  sleep 10
-  checkSuricataService
-  # make while true as while suriActive???
-done
 
+# while true ; do
+#     checkSuricataStatus
+#     sleep 5
+# done #>/dev/null 2>&1
+
+
+while : ; do
+    [[ ! -f "$_PROJECT_DIR_TMP/suriGUIDaemon.pid" ]] && break
+    echo "Pausing until file exists."
+    checkSuricataStatus
+    sleep 10
+done >/dev/null 2>&1
 exit 0
