next

diff --git a/suriGUI b/suriGUI
--- a/suriGUI
+++ b/suriGUI
@@ -1,20 +1,19 @@
 #!/usr/bin/env bash
 #
 # coder: ro0t
-
+# stamp: 2022-01-11
+#
 # God Mode: On
 set -o nounset      # Exit on undefined variable
 set -o errexit      # Exit on non-zero status
 set -o pipefail     # Pipe return exit status
 
+trap 'echo "$BASH_COMMAND" failed with error code $?' ERR
 
 if [ "$EUID" -ne 0 ]; then
   echo "Please run as root"
   exit 1
 fi
-
-
-trap 'echo "$BASH_COMMAND" failed with error code $?' ERR
 
 
 function exitSuriGUI() {
@@ -170,43 +169,6 @@ function updateConfigFile() {
   d3bug
 
   case "$1" in
-    "tab1" )
-      sed -i "s/^\(autostart\s*=\s*\).*\$/\1$2/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/^\(notifications\s*=\s*\).*\$/\1$3/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/^\(timeout\s*=\s*\).*\$/\1$4/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/^\(position\s*=\s*\).*\$/\1$5/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/^\(snooze\s*=\s*\).*\$/\1$6/" "$_PROJECT_CONFIG_FILE"
-
-      d3bug info "Autostart: $2"
-      d3bug info "Notifications: $3"
-      d3bug info "Timeout: $4 second(s)"
-      d3bug info "Position: $5"
-      d3bug info "Snooze: $5 second(s)"
-
-      #[[ $2 == "TRUE" ]] && startNotifDaemon || stopNotifDaemon
-    ;;
-    "tab2" )
-      sed -i "s/^\(keep\s*=\s*\).*\$/\1$2/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/^\(duration\s*=\s*\).*\$/\1$3/" "$_PROJECT_CONFIG_FILE"
-
-      d3bug info "Keep log: $2"
-      d3bug info "Log duration: $3"
-    ;;
-    "tab3" )
-      newAction="$2"
-      readConfigFile action && oldAction="$configAction"
-
-      sed -i "s/^\(action\s*=\s*\).*\$/\1$2/" "$_PROJECT_CONFIG_FILE"
-      sed -i "s/\<$oldAction\>/$newAction/" "$_SURICATA_RULES"
-
-      sed -i "s/^\(update\s*=\s*\).*\$/\1$3/" "$_PROJECT_CONFIG_FILE"
-
-      d3bug info "New rule action: $newAction"
-      d3bug info "Update rules every $3 days"
-    ;;
-
-
-
     "rules" )
       sed -i "s/\<$3\>/$2/" "$_SURICATA_RULES"
       checkSuricataStatus >/dev/null
@@ -612,16 +574,16 @@ function checkInternetConnection() {
   d3bug
 
   if ping -q -c 1 -W 1 github.com >/dev/null ; then
-    d3bug info "Internet connection active."
+    d3bug info "Internet connection is active"
   else
-    d3bug error "No internet connection. Trying Qubes Proxy..."
+    d3bug error "No internet connection. Trying with Qubes proxy"
 
     export https_proxy=127.0.0.1:8082
     if ping -q -c 1 -W 1 github.com >/dev/null ; then
-      d3bug error "Check your internet connection. Exiting..."
+      d3bug error "Internet connection not active. Exit 1"
       exit 1
     else
-      d3bug info "Internet found behing Qubes Proxy. Resuming update..."
+      d3bug info "Internet found behing Qubes Proxy"
     fi
   fi
 }
@@ -634,7 +596,7 @@ function updateSuricataRules() {
   checkInternetConnection
 
   readConfigFile action
-  oldAction=$configAction
+  oldAction="$configAction"
 
   if command -v suricata-update &>/dev/null ; then
     d3bug info "Downloading suricata rules ..."
@@ -645,27 +607,23 @@ function updateSuricataRules() {
       d3bug info "Download done"
 
       echo "$dateShort" > "$_SURICATA_UPDATE_TIMESTAMP"
-      d3bug info "Update finished."
+      d3bug info "Update finished @ $dateLong"
 
     else
-      d3bug error "Error updating Suricata rules. Exiting..."
+      d3bug error "Error updating Suricata rules. Exit 1"
       exit 1
     fi
   else
-    d3bug error "suricata-update not installed. Aborting"
+    d3bug error "suricata-update not installed. Exit 1"
     exit 1
   fi
 
   if [[ $oldAction != "alert" ]] ; then
-    updateConfigFile action $oldAction
+    updateConfigFile action "$oldAction"
     updateConfigFile rules alert "$oldAction"
   fi
-
-
 }
 export -f updateSuricataRules
-
-
 
 
 function startSuriGUI() {
@@ -689,13 +647,13 @@ function checkSuricataStatus() {
   d3bug
 
   if systemctl is-active --quiet suricata; then
-    if [[ $(pstree -p $(cat $_SURICATA_PID) | perl -ne 'print "$1\n" while /\((\d+)\)/g' 2>/dev/null | wc -l  ) -gt 1 ]] ; then
+    #if [[ $(pstree -p $(cat $_SURICATA_PID) | perl -ne 'print "$1\n" while /\((\d+)\)/g' 2>/dev/null | wc -l  ) -gt 1 ]] ; then
       d3bug info "Suricata is active"
       updateTrayMenu active
       export suricataStatus=active
-    else
-      export suricataStatus=inactive
-    fi
+    #lse
+    #  export suricataStatus=inactive
+    #fi
   else
     d3bug info "Suricata is inactive"
     updateTrayMenu inactive
