trying to get new notifications

diff --git a/suriGUI b/suriGUI
--- a/suriGUI
+++ b/suriGUI
@@ -13,26 +13,24 @@ function _GLOBAL_VARS()
 {
   export _PROJECT_NAME="suriGUI"
   export _PROJECT_DESCRIPTION="GUI for Suricata IPS and Qubes OS"
-  export _PROJECT_VER="1.5"
-  export _PROJECT_BUILD="2022-04-03"
+  export _PROJECT_VER="0.1.6"
+  export _PROJECT_BUILD="2022-04-09"
 
-  export timeShort=$(date +"%H:%M:%S")
-  export dateShort=$(date +"%Y-%m-%d")
-  export dateLong=$(date +"%Y-%m-%d-%H-%M-%S")
-
+  # DIRs
   export _PROJECT_DIR="/usr/share/suriGUI"
-  export _PROJECT_DIR_RES="$_PROJECT_DIR/res"
-  export _PROJECT_DIR_TMP="$_PROJECT_DIR/tmp"
-  export _PROJECT_DIR_LOG="$_PROJECT_DIR/log/$dateShort"
   export _PROJECT_DIR_CONF="$_PROJECT_DIR/conf"
-
+  export _PROJECT_DIR_RES="$_PROJECT_DIR/res"
+  export _PROJECT_DIR_LOG="$_PROJECT_DIR/log/$(date +"%Y-%m-%d")"
+  export _PROJECT_DIR_TMP="$_PROJECT_DIR/tmp"
   export _PROJECT_CONFIG_FILE="$_PROJECT_DIR_CONF/suriGUI.conf"
   export _NOTIF_IGNORE_LIST="$_PROJECT_DIR_CONF/ignore.sid"
 
+  # PIPEs
   export _PROJECT_PIPE="$_PROJECT_DIR_TMP/suriGUI.pipe"
   export _SID_IGNORE_PIPE="$_PROJECT_DIR_TMP/SIDignore.pipe"
   export _SID_CUSTOM_PIPE="$_PROJECT_DIR_TMP/SIDcustom.pipe"
 
+  # ICONs
   export _PROJECT_ICON="$_PROJECT_DIR_RES/suriGUI.png"
   export _PROJECT_ICON_INACTIVE="$_PROJECT_DIR_RES/icons/inactive.png"
   export _PROJECT_ICON_ACTIVE="$_PROJECT_DIR_RES/icons/active.png"
@@ -42,15 +40,20 @@ function _GLOBAL_VARS()
   export _PROJECT_ICON_MENU_STOP="$_PROJECT_DIR_RES/icons/stop.png"
   export _PROJECT_ICON_MENU_UPDATE="$_PROJECT_DIR_RES/icons/update.png"
 
+  # FILEs
   export _SURICATA_CONFIG="$_PROJECT_DIR_CONF/suricata.yaml"
   export _SURICATA_RULES="$_PROJECT_DIR_CONF/suricata.rules"
   export _SURICATA_CUSTOM_RULES="$_PROJECT_DIR_CONF/suriGUI.rules"
   export _SURICATA_UPDATE_TIMESTAMP="$_SURICATA_RULES.timestamp"
-  #export _SURICATA_OUTDATE="7"
+  export _SURIGUI_LOG_FILE="$_PROJECT_DIR_LOG/suriGUI.log"
 
-  # export _SURICATA_PID="$_PROJECT_DIR_TMP/suricata.pid"
+  # PIDs
   export _PROJECT_PID="$_PROJECT_DIR_TMP/suriGUI.pid"
   export _NOTIF_PID="$_PROJECT_DIR_TMP/suriNotif.pid"
+
+  # ARRAYs
+  _PROJECT_DB_DIRS=( "$_PROJECT_DIR" "$_PROJECT_DIR_CONF" "$_PROJECT_DIR_RES" "$_PROJECT_DIR_LOG" "$_PROJECT_DIR_TMP")
+  _PROJECT_DB_REQS=( "libnetfilter-queue-dev" "suricata" "jq" "yad" )
 }
 
 function exitSuriGUI()
@@ -69,12 +72,13 @@ function exitSuriGUI()
 
   # Cleaning temp files
   find "$_PROJECT_DIR_TMP" -type f -name "*.pipe" -delete
-  find "$_PROJECT_DIR_TMP" -type f -name "*.pid" -delete
+  #find "$_PROJECT_DIR_TMP" -type f -name "*.pid" -delete
   find "$_PROJECT_DIR_TMP" -type f -name "*.tab" -delete
-  find "$_PROJECT_DIR_TMP" -type f -name "*.lock" -delete
+
 
   d3bug info "EXIT 0"
-  # sudo pkill -f suriGUI
+  #exit 0
+  sudo pkill -f suriGUI
 }
 
 function d3bug()
@@ -242,44 +246,84 @@ function editSID()
 
 
   # Comment SID in suricata rules, disable it
-  sed -i "/^[^#]/ s/\(^.*$sid.*$\)/#\1/" "$_SURICATA_RULES"
-
-  d3bug info "SID: $sid unblocked. Reloading rules..."
-  sudo suricatasc -c reload-rules
-  d3bug info "Done"
+  # sed -i "/^[^#]/ s/\(^.*$sid.*$\)/#\1/" "$_SURICATA_RULES"
+  #
+  # d3bug info "SID: $sid unblocked. Reloading rules..."
+  # sudo suricatasc -c reload-rules
+  # d3bug info "Done"
 }
 
-function ignoreSID()
+# function ignoreSID()
+# {
+#   d3bug
+#
+#   local sid="$1"
+#
+#   local TXT="Disable notifications for SID: $sid ?\n"
+#   local TXT+="You will no longer see any info when SID is blocked."
+#
+#   yad \
+#     --image="$_PROJECT_ICON" \
+#     --image-on-top \
+#     --width=450 \
+#     --title="$_PROJECT_NAME" \
+#     --button="Yes" --button="No" \
+#     --text="$TXT" \
+#   &>/dev/null
+#   ret=$?
+#
+#   if [ "$ret" = 0 ]
+#   then
+#     if ! grep -q "$sid" "$_NOTIF_IGNORE_LIST"
+#     then
+#       d3bug info "Writing SID $sid in ignore list"
+#       echo "$sid" >> $_NOTIF_IGNORE_LIST
+#     else
+#       d3bug info "SID already in ignore list"
+#     fi
+#   else
+#     d3bug info "Nothing done"
+#   fi
+# }
+
+function preventSuricataSpam()
+{
+  d3bug
+  local sid="$1"
+  local currentLog="$2"
+
+  d3bug info "Current log: $currentLog"
+
+  if grep -q "$currentLog" "$_SURIGUI_LOG_FILE"
+  then
+    d3bug error "Spam message"
+    stopSpam="TRUE"
+  else
+    d3bug info "Not found in suriGUIlog"
+    echo "$suriGUIlog" >> "$_SURIGUI_LOG_FILE"
+    d3bug info "Output written"
+    stopSpam="FALSE"
+  fi
+}
+
+
+function checkIgnoreSidList()
 {
   d3bug
 
   local sid="$1"
-  local TXT="Disable notifications for SID: $sid ?\n"
-  local TXT+="You will no longer see any info when SID is blocked."
 
-  yad \
-    --image="$_PROJECT_ICON" \
-    --image-on-top \
-    --width=450 \
-    --title="$_PROJECT_NAME" \
-    --button="Yes" --button="No" \
-    --text="$TXT" \
-  &>/dev/null
-  ret=$?
-
-  if [ "$ret" = 0 ]
+  if grep -q "$sid" "$_NOTIF_IGNORE_LIST"
   then
-    if ! grep -q "$sid" "$_NOTIF_IGNORE_LIST"
-    then
-      d3bug info "Writing SID $sid in ignore list"
-      echo "$sid" >> $_NOTIF_IGNORE_LIST
-    else
-      d3bug info "SID already in ignore list"
-    fi
+    d3bug error "SID: $sid is on ignore list"
+    ignoreSID="TRUE"
   else
-    d3bug info "Nothing done"
+    d3bug info "SID: $sid is not on ignore list"
+    ignoreSID="FALSE"
   fi
 }
+
+
 
 function send_notif()
 {
@@ -292,11 +336,10 @@ function send_notif()
   local src=${5:-SRC}
   local dest=${6:-DEST}
   local action=${7:-Action}
-  local sidLockFile="$_PROJECT_DIR_TMP/$sid.lock"
 
-
+echo "1"
   case "$type" in
-    info )
+    "info")
       yad \
       --title="$_PROJECT_NAME v.$_PROJECT_VER" \
       --image="$_PROJECT_ICON" \
@@ -304,13 +347,16 @@ function send_notif()
       --button="Yes" --button="No" \
       --text="$cat" &
     ;;
-    alert )
-      if grep -q "$sid" "$_NOTIF_IGNORE_LIST"
+    "alert")
+      suriGUIlog="$(date +'%Y-%m-%d')|$(date +'%H:%M:%S')|$sid|$src|$dest"
+
+      checkIgnoreSidList "$sid"
+      if [[ "${ignoreSID:-}" == "FALSE" ]]
       then
-        d3bug info "Ignore SID: $sid"
-      else
-        if [[ ! -f "$sidLockFile" ]]
+        preventSuricataSpam "$sid" "$suriGUIlog"
+        if [[ "${stopSpam:-}" == "FALSE" ]]
         then
+          echo "show notif now"
           readConfigFile timeout
           readConfigFile notificationPosition
 
@@ -321,16 +367,14 @@ function send_notif()
             * )               pos="--posx=-1 --posy=-1"  ;;
           esac
 
-          touch "$sidLockFile"
-          set +o errexit
-
           TXT="<b>${cat:-Potentially Bad traffic}</b>\n"
-          TXT+="$dateShort  at  $timeShort \n"
+          TXT+="$(date +'%Y-%m-%d') at  $(date +'%H:%M:%S') \n"
           TXT+="<i>$sig</i>"
 
           ACTIONcontrol="Continue blocking!Don't show again!Edit rule"
 
-          action=$( yad \
+          set +o errexit # yad problem, error exit must be disabled
+          yadOutput="$( yad \
             --title="suriNotif" ${pos:-} \
             --form \
             --on-top \
@@ -345,37 +389,44 @@ function send_notif()
             --field="Source IP:RO" "$src" \
             --field="Destination IP:RO" "$dest" \
             --field="Action:CB" "$ACTIONcontrol" \
-            --button="OK":10
-          )
-
+            --button="OK":10)"
           ret=${?:-70}
+          set -o errexit
+          d3bug info "Return: $ret"
+
           case "$ret" in
             10 )
-              action="${action[3]}"
-              d3bug info "Selected action: $action"
+              # action="${actions[@]}"
+              readarray -d '|' -t array <<< $(echo $yadOutput)
+              d3bug info "Selected action: ${array[3]}"
 
-              case "$action" in
+              case "${array[3]}" in
                 "Continue blocking")
                   : # Do nothing
+                  #write to overview and ignore for today
                 ;;
 
                 "Don't show again")
-                  ignoreSID "$sid"
+                  if ! grep -q "$sid" "$_NOTIF_IGNORE_LIST"
+                  then
+                    d3bug info "Writing SID: $sid to ignore list"
+                    echo "$sid" >> $_NOTIF_IGNORE_LIST
+                  else
+                    d3bug info "SID: $sid is already in ignore list"
+                  fi
                 ;;
 
                 "Edit rule")
-                  editSID "$sid"
+                  editSID "$sid" "$cat" "$src" "$dest" "$action"
                 ;;
+                *) d3bug error "Can't read action" ;;
               esac
             ;;
             # 20 )  editSID "$sid" "$cat" "$src" "$dest" "$action" ;;
             70 )  d3bug info "Timeout for notification: $sid"   ;;
             252 ) d3bug info "Escape key pressed"   ;;
-            * )   :    ;;
+            * )   echo "error"    ;;
           esac
-
-          [[ -f "$sidLockFile" ]] && rm "$sidLockFile"
-          set -o errexit
         fi
       fi
     ;;
@@ -398,7 +449,7 @@ function updateSuriGUI()
     fi
   fi
   d3bug info "Updating done"
-  send_notif info "No update found"
+  send_notif "info" "No update found"
 }
 
 function deleteIgnoredSID()
@@ -608,7 +659,7 @@ function stopNotifDaemon()
 
   if [[ -f "$_NOTIF_PID" ]]
   then
-    pkill -P "$(cat $_NOTIF_PID)" &>/dev/null # kill process and all children
+    pkill -P "$(cat $_NOTIF_PID)" #&>/dev/null # kill process and all children
     rm "$_NOTIF_PID"
     d3bug info "suriNotif stopped"
   else
@@ -625,7 +676,7 @@ function startNotifDaemon()
     | jq --unbuffered -r '@sh  "sid=\(.alert.signature_id) category=\(.alert.category) signature=\(.alert.signature) SRC=\(.src_ip) DEST=\(.dest_ip)  action=\(.alert.action)"' \
       | while read -r line; do \
         eval "$line" ; \
-        send_notif alert "$category" "$signature" "$sid" "$SRC" "$DEST" "$action" ; \
+        send_notif "alert" "$category" "$signature" "$sid" "$SRC" "$DEST" "$action" ; \
       done ) &
 
   echo "$!" > "$_NOTIF_PID"
@@ -653,20 +704,22 @@ function updateTrayMenu()
   case "$status" in
     "active")   menu="Stop!bash -c 'controlSuricataService stop'" ;;
     "inactive") menu="Start!bash -c 'controlSuricataService start'" ;;
-    # "starting") menu="" ;;
-    *)          exit 1 ;;
+    *)          menu="" ;;
   esac
 
   #export icon="$_PROJECT_DIR_RES/icons/settings.png"
   #xdg-icon-resource install --context mimetypes --size 48 "$_PROJECT_DIR_RES/icons/settings.png" "$_PROJECT_NAME-settings"
 
   menu+="||Settings!bash -c 'suriGUISettings'"
+  menu+="||Reload suricata rules!bash -c 'sudo suricatasc -c reload-rules'"
+  menu+="|Update suricata rules!bash -c 'updateSuricataRules'"
   menu+="||Update!bash -c updateSuriGUI"
   menu+="||Exit!quit"
 
   [[ -p $_PROJECT_PIPE ]] && exec 3<>$_PROJECT_PIPE echo "menu:$menu" >&3 &
 
   d3bug info "Menu updated: $status"
+  d3bug info "Menu: $menu"
 
   [[ -p $_PROJECT_PIPE ]] && exec 3<>$_PROJECT_PIPE echo "icon:$suricataStatus" >&3 &
 
@@ -713,8 +766,8 @@ function updateSuricataRules()
     then
       d3bug info "Download done"
 
-      echo "$dateShort" > "$_SURICATA_UPDATE_TIMESTAMP"
-      d3bug info "Update finished @ $dateLong"
+      echo "$(date +'%Y-%m-%d')" > "$_SURICATA_UPDATE_TIMESTAMP"
+      d3bug info "Update finished $(date +'%Y-%m-%d') @ $(date +'%H:%M:%S')"
 
 
       # d3bug info "Starting reload Suricata rules..."
@@ -759,9 +812,15 @@ function checkSuricataStatus()
 
   if systemctl is-active --quiet suricata
   then
-    export suricataStatus=active
+    export suricataStatus="active"
   else
-    export suricataStatus=inactive
+    export suricataStatus="inactive"
+    d3bug error "Suricata is inactive. trying to restart..."
+    if sudo systemctl restart suricata
+    then
+      sleep 10
+      d3bug info "Suricata restarted"
+    fi
   fi
 
   d3bug info "Suricata is $suricataStatus"
@@ -885,15 +944,24 @@ function checkProjectConfigFiles ()
 
   local files=( "$_PROJECT_CONFIG_FILE"
                 "$_SURICATA_CUSTOM_RULES"
-                "$_NOTIF_IGNORE_LIST" )
+                "$_NOTIF_IGNORE_LIST"
+                "$_SURIGUI_LOG_FILE"
+                 )
 
   for file in "${files[@]}"
   do
     if [[ ! -f "$file" ]]
     then
-      d3bug error "Config not found: $file"
+      d3bug error "${file##*.} not found: $file"
       fileName=$(basename $file)
-      if ( cp "$_PROJECT_DIR_CONF/default/$fileName.default" "$_PROJECT_DIR_CONF/$fileName" )
+      if [[ "${file##*.}" = "log" ]]
+      then
+        destination="$_PROJECT_DIR_LOG/$fileName"
+      else
+        destination="$_PROJECT_DIR_CONF/$fileName"
+      fi
+
+      if ( cp "$_PROJECT_DIR_CONF/default/$fileName.default" "$destination" )
       then
         d3bug info "Config created"
       else
@@ -901,21 +969,49 @@ function checkProjectConfigFiles ()
         exit 1
       fi
     else
-      d3bug info "Local config found: $file"
+      d3bug info "Local ${file##*.} found: $file"
     fi
   done
 }
+
+function checkDirPermission ()
+{
+  d3bug
+
+  for dir in ${_PROJECT_DB_DIRS[@]}
+  do
+    if [[ -d "$dir" ]]
+    then
+      d3bug info "Inspecting directory: $dir"
+      if [[ -w "$dir" ]]
+      then
+        d3bug info "Directory writable"
+      else
+        d3bug error "Directory not writable."
+
+        if sudo chown user:user "$dir" -R
+        then
+          d3bug info "Directory owned"
+        else
+          d3bug error "Something is wrong with folder/permission"
+          exit 1
+        fi
+      fi
+    else
+      echo "not dir"
+    fi
+  done
+
+}
+
 
 function checkProjectRequirements ()
 {
   d3bug
 
-  local apps=( "libnetfilter-queue-dev"
-                "suricata"
-                "jq"
-                "yad" )
 
-  for app in "${apps[@]}"
+
+  for app in "${_PROJECT_DB_REQS[@]}"
   do
     if dpkg -s "$app" &>/dev/null
     then
@@ -986,6 +1082,7 @@ export -f updateSuriGUI
 # S T A R T   S U R I G U I
 _GLOBAL_VARS
 checkProjectRequirements
+checkDirPermission
 checkProjectDirectories
 checkProjectConfigFiles
 
