delete restore detete restorerersdedsdadasd

diff --git a/suriGUI b/suriGUI
--- a/suriGUI
+++ b/suriGUI
@@ -8,12 +8,16 @@ set -o pipefail     # Pipe return exit status
 trap 'd3bug error "$BASH_COMMAND" failed with error code $?' ERR
 trap exitSuriGUI EXIT SIGUSR1 SIGUSR2
 
-#23-23
+# opt version only
+#todo: show icon at start to show if program at least run
+#todo: make new app for showing that suricata/IPS is starting
+# make service and kill it as soon as suriGUI started
+
 # GLOBAL VARIABLES
 # INFO
 export _PROJECT_NAME="suriGUI"
 export _PROJECT_DESCRIPTION="GUI for Suricata"
-export _PROJECT_VER="0.2.220802"
+export _PROJECT_VER="0.2.220803"
 
 #
 # DIRs
@@ -64,8 +68,9 @@ _PROJECT_DB_PIPES=( "$_PROJECT_PIPE_MAIN"
 #
 # ICONs
 export _PROJECT_ICON_MAIN="$_PROJECT_DIR_RES/suriGUI.png"
-export _PROJECT_ICON_INACTIVE="$_PROJECT_DIR_RES/icons/inactive.png"
-export _PROJECT_ICON_ACTIVE="$_PROJECT_DIR_RES/icons/active.png"
+export _PROJECT_ICON_INACTIVE="$_PROJECT_DIR_RES/icons/suriGUI/inactive.png"
+export _PROJECT_ICON_ACTIVE="$_PROJECT_DIR_RES/icons/suriGUI/active.png"
+export _PROJECT_ICON_ALERT="$_PROJECT_DIR_RES/icons/notif/alert.png"
 
 _PROJECT_DB_ICONS=( "$_PROJECT_ICON_MAIN"
                     "$_PROJECT_ICON_INACTIVE"
@@ -87,7 +92,8 @@ _PROJECT_DB_REQS=( "libnetfilter-queue-dev"
 
 function exitSuriGUI()
 # Trap any exit signal and execute this function
-# Remove all tmp files (and log if enabled)
+# Remove all tmp files
+# todo: implement log deletion based on settings configuration
 {
 
   echo "EXITing"
@@ -106,6 +112,7 @@ function exitSuriGUI()
   find "$_PROJECT_DIR_TMP" -type f -name "*.tmp" -delete &>/dev/null
   find "$_PROJECT_DIR_TMP" -type f -name "*.tab" -delete &>/dev/null
 
+  #todo: delete all files and foolders in tmp
 
   d3bug info "good luck"
 
@@ -125,13 +132,14 @@ function exitSuriGUI()
   exit 0
 
   # Kill project and Suricata
-  #pkill -f suriGUI
+  #sudo pkill -f suriGUI
 }
 
 
 function d3bug()
 # Print output messages, function names, errors
 # Usage: d3bug info|error "Lorem ipsum dolor sit amet"
+# todo: add verbosity and no output, error only
 {
   local type="${1:-*}"
   local msg="${2:-}"
@@ -159,24 +167,21 @@ function d3bug()
 }
 
 
+
+# Engage!
 echo -e \
-"
-
-####################
-# $_PROJECT_NAME          #
+"####################
+#     $_PROJECT_NAME      #
 # $_PROJECT_DESCRIPTION #
-# $_PROJECT_VER       #
+# build $_PROJECT_VER #
 ####################"
-
-#\
-   #| tee -a "$_PROJECT_FILE_LOG"
 
 
 
 function readConfigFile()
-# Read suriGUI.conf and export all variables for yad
+# Read suriGUI.conf and export all variables to yad
 # Yad is not working if export is not done
-# will be removed and replaced with settings.yaml
+# todo: remove and replace with suriGUI.yaml
 {
   d3bug
   local config="${1:-*}"
@@ -246,9 +251,9 @@ function updateConfigFile()
       # if [[ "$suricataStatus" == "active" ]]
       # then
       #   d3bug info "Starting Suricata reload..."
-      #   if suricatasc -c reload-rules
+      #   if sudo suricatasc -c reload-rules
       #   then
-      #     #systemctl reload suricata #&>/dev/null
+      #     #sudo systemctl reload suricata #&>/dev/null
       #     d3bug info "Rules updated & reloaded"
       #   else
       #     d3bug error "Can't reload rules??"
@@ -538,8 +543,8 @@ function send_notif()
             --width=500 \
             --timeout="$CONF_global_notifications_duration" \
             --timeout-indicator="top" \
-            --window-icon="res/suriGUI.png" \
-            --image="res/alert_64.png" \
+            --window-icon="$_PROJECT_ICON_ALERT" \
+            --image="$_PROJECT_ICON_ALERT" \
             --image-on-top \
             --text="$TXT" \
             --field="SID:RO" "$sid" \
@@ -684,6 +689,7 @@ function suriGUISettings()
 # Ignored SID List
 # Custom Rules List - will be replaced
 # Backup/Restore - Not done yet
+# todo: preview log in tab, create new tab: log
 {
   d3bug
 
@@ -860,7 +866,7 @@ function stopNotifDaemon()
   if [[ -f "$_PROJECT_PID_NOTIF" ]]
   then
     # if pkill -P "$(cat $_PROJECT_PID_NOTIF)"
-    if kill -9 "$(cat $_PROJECT_PID_NOTIF)" #&>/dev/null
+    if sudo kill -9 "$(cat $_PROJECT_PID_NOTIF)" #&>/dev/null
     then
       rm "$_PROJECT_PID_NOTIF"
       d3bug info "suriNotif stopped"
@@ -901,7 +907,7 @@ function controlSuricataService()
   # stop | start
   local action="$1"
 
-  if systemctl "$action" suricata &>/dev/null
+  if sudo systemctl "$action" suricata &>/dev/null
   then
     d3bug ok "$action Suricata service"
   else
@@ -927,7 +933,7 @@ function updateTrayMenu()
   #export icon="$_PROJECT_DIR_RES/icons/settings.png"
   #xdg-icon-resource install --context mimetypes --size 48 "$_PROJECT_DIR_RES/icons/settings.png" "$_PROJECT_NAME-settings"
 
-  # menu+="||Reload suricata rules!bash -c 'suricatasc -c reload-rules'"
+  # menu+="||Reload suricata rules!bash -c 'sudo suricatasc -c reload-rules'"
   # menu+="|Update suricata rules!bash -c 'updateSuricataRules'"
   menu+="|Restart Suricata service!bash -c 'controlSuricataService restart'"
   menu+="||Settings!bash -c 'suriGUISettings'"
@@ -1009,7 +1015,7 @@ function checkSuricataStatus()
     export suricataStatus="inactive"
 
     d3bug error "Suricata is inactive."
-    # if systemctl restart suricata
+    # if sudo systemctl restart suricata
     # then
     #   sleep 10
     #   d3bug info "Suricata restarted"
@@ -1090,7 +1096,7 @@ function reloadSuricataRules()
 
   d3bug info "Realoading rules ..."
 
-  if suricatasc -c reload-rules &>/dev/null
+  if sudo suricatasc -c reload-rules &>/dev/null
   then
     d3bug ok "Rules reloaded @ $(date +'%Y-%m-%d') $(date +'%H:%M:%S')"
   else
@@ -1105,13 +1111,15 @@ function updateSuricataRules()
 {
   d3bug
 
+
+
   if command -v suricata-update &>/dev/null
   then
     d3bug info "Starting update ..."
 
     if suricata-update  --output "$_PROJECT_DIR_SURICATA" \
                         --data-dir "$_PROJECT_DIR_TMP" \
-                        --no-test &>/dev/null
+                        --no-test #&>/dev/null
     then
       echo "$(date +'%Y-%m-%d')" > "$_PROJECT_FILE_SURICATA_RULES_TIMESTAMP"
       d3bug ok "Update done @ $(date +'%Y-%m-%d') $(date +'%H:%M:%S')"
@@ -1123,6 +1131,7 @@ function updateSuricataRules()
     fi
   else
     d3bug error "suricata-update not installed. Exit 1"
+    #todo: maybe not exit if default file is there
     exit 1
   fi
 }
@@ -1270,26 +1279,79 @@ function checkProjectFiles()
 {
   d3bug
 
+  local defStorage="$_PROJECT_DIR_CONF/default"
+
   for file in "${_PROJECT_DB_FILES[@]}"
   do
-    if [[ ! -f "$file" ]]
-    then
-      d3bug error "File not found: $file"
       fileName=$(basename $file)
       destination="$(dirname "${file}")"
+      backupFile="$defStorage/$fileName"
 
-      if ( cp "$_PROJECT_DIR_CONF/default/$fileName" "$destination" &>/dev/null)
+      if [[ ! -e "$file"  ]]
       then
-        d3bug ok "File created: $file"
-      else
-        d3bug error "Can't copy default config file: \"$fileName\" to directory: \"$destination\""
-        exit 1
+        d3bug error "File not found: $file"
+
+        if [[ -e "$backupFile" ]]
+        then
+          d3bug info "Backup file found"
+          if cp "$backupFile" "$destination"
+          then
+            d3bug info "File restored: $fileName"
+          else
+            d3bug error "Can't copy default config file: \"$fileName\" to directory: \"$destination\""
+            exit 1
+          fi
+        else
+          if touch "$file"
+          then
+            d3bug ok "File created: $file"
+          else
+            d3bug error "Can't create config file: \"$fileName\" in directory: \"$destination\""
+            # todo: try to inspect if dir is there
+            # chown
+            exit 1
+          fi
+        fi
+      #else
       fi
-    else
-      # d3bug info "Local ${file##*.} found: $file"
-      d3bug ok "$file"
-    fi
+
   done
+
+  d3bug ok "$file"
+
+  # for file in "${_PROJECT_DB_FILES[@]}"
+  # do
+  #
+  #   # todo: if file is not in default folder, touch it
+  #
+  #   # local defStorage="$_PROJECT_DIR_CONF/default"
+  #   # fileName=$(basename $file)
+  #   #
+  #   #
+  #   # echo "full file path: $file"
+  #   # echo "fileName: $fileName"
+  #   # if [[ ! -e "$defStorage/$fileName" ]]
+  #   # then
+  #   #   echo "touch $file"
+  #   # fi
+  #   if [[ ! -f "$file" ]]
+  #   then
+  #     d3bug error "File not found: $file"
+  #     fileName=$(basename $file)
+  #     destination="$(dirname "${file}")"
+  #
+  #     if cp "$_PROJECT_DIR_CONF/default/$fileName" "$destination"
+  #     then
+  #       d3bug ok "File created: $file"
+  #     else
+  #       d3bug error "Can't copy default config file: \"$fileName\" to directory: \"$destination\""
+  #       exit 1
+  #     fi
+  #   else
+  #     # d3bug info "Local ${file##*.} found: $file"
+  #     d3bug ok "$file"
+  #   fi
+  # done
 }
 
 
@@ -1345,11 +1407,12 @@ function checkProjectDependencies()
           --title="$_PROJECT_NAME" \
           --button="Yes" --button="No" \
           --text="$app is not installed.\nDo you want to install it now?" &>/dev/null
+
       ret=$?
       if [[ $ret = 0 ]]
       then
         d3bug info "Installing $app ..."
-        if apt-get install "$app" -y &>/dev/null
+        if sudo apt-get install "$app" -y &>/dev/null
         then
           d3bug ok "$app was successfully installed"
         else
