update

diff --git a/suriGUI b/suriGUI
--- a/suriGUI
+++ b/suriGUI
@@ -38,10 +38,11 @@ function createDir() {
 export -f createDir
 
 
-export dateShort=$(date +"%H:%M:%S")
+export timeShort=$(date +"%H:%M:%S")
+export dateShort=$(date +"%Y-%m-%d")
 export dateLong=$(date +"%Y-%m-%d-%H-%M-%S")
 
-export _PROJECT_NAME="suriGUI" && echo -e "$dateShort \e[42;30m  $_PROJECT_NAME  \e[0m"
+export _PROJECT_NAME="suriGUI" && echo -e "$timeShort \e[42;30m  $_PROJECT_NAME  \e[0m"
 
 export _PROJECT_VER="0.5"
 export _PROJECT_BUILD="2021-12-04"
@@ -57,6 +58,7 @@ export _PROJECT_PIPE="$_PROJECT_DIR_TMP/suri.pipe"
 export _PROJECT_ICON="$_PROJECT_DIR_RES/suriGUI.png"
 export _PROJECT_ICON_INACTIVE="$_PROJECT_DIR_RES/inactive-icon.png"
 export _PROJECT_ICON_ACTIVE="$_PROJECT_DIR_RES/active-icon.png"
+export _PROJECT_LOCK="$_PROJECT_DIR_TMP/$_PROJECT_NAME.lock"
 
 export _SURICATA_CONFIG_IDS="$_PROJECT_DIR_CONF/suricataIDS.yaml"
 export _SURICATA_CONFIG_IPS="$_PROJECT_DIR_CONF/suricataIPS.yaml"
@@ -64,11 +66,13 @@ export _SURICATA_RULES="$_PROJECT_DIR_CONF/suricata.rules"
 export _SURICATA_UPDATE_TIMESTAMP="$_SURICATA_RULES.timestamp"
 export _SURICATA_LOG="$_PROJECT_DIR_LOG/$_PROJECT_NAME-$dateLong.log"
 export _SURICATA_OUTDATE="14"
+
 export _SURICATA_PID="$_PROJECT_DIR_TMP/suricata.pid"
+export _PROJECT_PID="$_PROJECT_DIR_TMP/suriGUI.pid"
 
 
 function exitSuriGUI() {
-  echo -e "$dateShort \e[41;30mEXITING...\e[0m"
+  echo -e "$timeShort \e[41;30mEXITING...\e[0m"
 
   for f in $(ls -1 $_PROJECT_DIR_TMP/*.pid) ; do
     d3bug info "Closing $f with PID $(cat $f)"
@@ -78,12 +82,10 @@ function exitSuriGUI() {
   rm "$_PROJECT_DIR_TMP" -R
   stopSuricataService exit
 
-  #[[ -d $_PROJECT_DIR_TMP ]] && rm "$_PROJECT_DIR_TMP" -R
 
 }
 export -f exitSuriGUI
-trap exitSuriGUI SIGINT SIGHUP SIGTERM SIGUSR1 SIGUSR2
-# trap "rm $_PROJECT_DIR_TMP -R" EXIT
+trap exitSuriGUI SIGINT SIGHUP SIGTERM SIGUSR1 SIGUSR2 EXIT
 
 function checkRequirements () {
   d3bug
@@ -191,6 +193,13 @@ export -f updateSuricataAction
 function updateSuricataMode() {
   d3bug
 
+  # check if running
+    #yes
+      # stop suricata and cchange service
+      #start suricata
+    #no
+      # change only config file
+
   d3bug info "Stopping Suricata service"
 
   stopSuricataService
@@ -225,7 +234,12 @@ function suriGUISettings() {
   KEY=$RANDOM
 
   yad --plug=$KEY --tabnum=1 --form \
-      --field="<b>In developement</b>":LBL "" \ &
+      --field="<b>In developement</b>":LBL "" \
+      \
+      --field="":LBL "" \
+      --field="<b>Files</b>":LBL "" \
+      --field="Auto start":chk "TRUE" \
+      --field="Start Suricata service on start":LBL "" &
   #echo $! > "$_PROJECT_DIR_TMP/tab1.pid"
 
   readConfigFile mode
@@ -312,24 +326,79 @@ function stopSuricataService() {
 export -f stopSuricataService
 
 
+
+function checkIptables() {
+  d3bug
+
+  d3bug info "mode: $1"
+
+  case "$1" in
+    "IDS" )
+            if iptables -C FORWARD -m mark ! --mark 1/1 -j NFQUEUE 1>&- 2>&- ; then
+              iptables -D FORWARD -m mark ! --mark 1/1 -j NFQUEUE
+              d3bug info "NFQueue deleted"
+            else
+              d3bug info "iptables already set"
+            fi
+      ;;
+    "IPS" )
+            if iptables -C FORWARD -m mark ! --mark 1/1 -j NFQUEUE 1>&- 2>&- ; then
+              d3bug info "iptables already set"
+            else
+              iptables -I FORWARD -m mark ! --mark 1/1 -j NFQUEUE
+              d3bug info "NFQueue set"
+            fi
+      ;;
+    * ) d3bug error "Suricata mode unknown. iptables not checked"
+        exit 1
+      ;;
+  esac
+
+
+}
+export -f checkIptables
+
+
+
 function startSuricataService() {
   d3bug
 
   source "$_PROJECT_CONFIG_FILE"
+  d3bug info "Mode: $mode"
+
+  #flock -n /var/lock/dobackup.lock ./dobackup.sh
+
 
   case "$mode" in
-    "IDS" ) config="-c $_SURICATA_CONFIG_IDS -i eth0"
-      ;;
-    "IPS" ) config="-c $_SURICATA_CONFIG_IPS -q 0"
-      ;;
-    * ) d3bug error "Suricata mode unknown."
-        exit 1
+    "IDS" ) config="-c $_SURICATA_CONFIG_IDS -i eth0" ;;
+    "IPS" ) config="-c $_SURICATA_CONFIG_IPS -q 0"    ;;
+    * )     d3bug error "Suricata mode unknown."
+            exit 1
       ;;
   esac
-  d3bug info "Starting Suricata in $mode mode"
 
-  [[ -f $_SURICATA_PID ]] && rm $_SURICATA_PID
+
+
+ if [[ -f "$_SURICATA_PID" ]] ; then
+   echo "suricata pid file already found"
+   if ps aux | grep $(cat $_SURICATA_PID) ; then
+    echo "exist and active"
+  else
+    echo "startingkkkkkkkkkkk"
+    /usr/bin/suricata $config --pidfile $_SURICATA_PID -S $_SURICATA_RULES  -l $_PROJECT_DIR_LOG  1>&- 2>&- &
+  fi
+else
+  echo "pid not found, starting suricata"
   /usr/bin/suricata $config --pidfile $_SURICATA_PID -S $_SURICATA_RULES  -l $_PROJECT_DIR_LOG  1>&- 2>&- &
+fi
+
+
+  checkIptables $mode
+
+
+
+
+
 }
 export -f startSuricataService
 
@@ -434,12 +503,14 @@ function updateSuricataRules() {
   if command -v suricata-update ; then
     if suricata-update --output "$_PROJECT_DIR_CONF" \
                        --data-dir "$_PROJECT_DIR_CONF" \
-                       --no-test >/dev/null ; then
-      if suricatasc -c ruleset-reload-nonblocking ; then
-        d3bug info "Rules reloaded"
+                       --no-test  ; then
+
+      checkSuricataStatus
+      if [[ $suricataStatus == "active" ]] ; then
+        suricatasc -c ruleset-reload-nonblockin
+        d3bug info "Rules updated & reloaded"
       else
-        d3bug error "New rules can not be applied. Exiting..."
-        exit 1
+        d3bug info "Rules updated"
       fi
 
       echo "$dateShort" > "$_SURICATA_UPDATE_TIMESTAMP"
@@ -496,7 +567,7 @@ function startSuriGUIDaemon() {
     --separator="|" \
     --menu="${suriTrayMenuList:-Exit!bash -c exitSuriGUI}" \
     --command="bash -c suriOnClick" <&3 &
-  echo $! > "$_PROJECT_DIR_TMP/suriGUIDaemon.pid"
+  echo $! > "$_PROJECT_PID"
 
   d3bug info "Daemon started"
 }
@@ -518,10 +589,10 @@ startSuriGUIDaemon
 
 
 while : ; do
-    [[ ! -f "$_PROJECT_DIR_TMP/suriGUIDaemon.pid" ]] && break
+    [[ ! -f "$_PROJECT_PID" ]] && break
     checkSuricataStatus
     sleep 3
 done >/dev/null 2>&1
 
-echo -e "$dateShort \e[41;30m  EXIT 0  \e[0m"
+echo -e "$timeShort \e[41;30m  EXIT 0  \e[0m"
 exit 0
